apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cassandra-db
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      volume: volume-cassandra-db
